baseURL = 'https://arda.pw/'
languageCode = 'en-us'
title = 'Arda Kılıçdağı'

# Coder Theme specific Start
# baseurl = "http://www.example.com"
# title = "johndoe"
theme = "hugo-coder"
# languagecode = "en"
defaultcontentlanguage = "en"

pagination.pagerSize = 10

disqusShortname = "ardapw"

[markup.highlight]
style = "github-dark"

# Execute unsafe HTML Markup
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
# Execute unsafe HTML Markup END

[params]
  author = "Arda Kılıçdağı"
  info = "Software Architect and Staff Engineer"
  description = "Arda Kılıçdağı's personal Website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/images/favicon.svg"
  favicon_32 = "/images/favicon-32x32.png"
  favicon_16 = "/images/favicon-16x16.png"

  since = 2013

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Ardakilic"
[[params.social]]
  name = "Stackoverflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 2
  url = "https://stackoverflow.com/users/570763/arda"
[[params.social]]
  name = "X"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://x.com/ardadev"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-brands fa-mastodon fa-2x"
  weight = 4
  url = "https://micro.arda.pw/@arda"
[[params.social]]
  name = "BlueSky"
  icon = "fa fa-cloud fa-2x"
  weight = 4
  url = "https://bsky.app/profile/arda.bsky.social"
[[params.social]]
  name = "Nostr"
  icon = "fa fa-crow fa-2x"
  weight = 4
  url = "https://primal.net/p/nprofile1qqszc4uglxka94u3nm3g6gjhn8yklxgjsc20ng0tmglmc7kmpwxyhwcva0fq8"
[[params.social]]
  name = "Reddit"
  icon = "fa fa-reddit fa-2x"
  weight = 5
  url = "https://www.reddit.com/user/ardakilic/"
[[params.social]]
  name = "Trakt"
  icon = "fa fa-tv fa-2x"
  weight = 6
  url = "https://trakt.tv/users/arda/"
[[params.social]]
  name = "IGDB"
  icon = "fa fa-gamepad fa-2x"
  weight = 7
  url = "https://www.igdb.com/users/ardakilicdagi"
[[params.social]]
  name = "Last.fm"
  icon = "fa fa-lastfm fa-2x"
  weight = 8
  url = "https://www.last.fm/user/ArdaDev"
[[params.social]]
  name = "Feed to this Site"
  icon = "fa fa-rss fa-2x"
  weight = 8
  url = "https://arda.pw/index.xml"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 9
  url = "https://www.linkedin.com/in/ardakilicdagi/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
# Coder Theme Specific END