baseURL = 'https://arda.org/'
languageCode = 'en-us'
title = 'Arda Kılıçdağı'

# Coder Theme specific Start
# baseurl = "http://www.example.com"
# title = "johndoe"
theme = "hugo-coder"
# languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "ardapw"

[markup.highlight]
style = "github-dark"

[params]
  author = "Arda Kılıçdağı"
  info = "Software Architect and Staff Engineer"
  description = "Arda Kılıçdağı's personal Website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2013

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Ardakilic"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 2
  url = "https://twitter.com/ardadev"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 3
  url = "https://micro.arda.pw/@arda"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
# Coder Theme Specific END